apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wuar-demo-ombq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wuar-demo-ombq
    app.kubernetes.io/part-of: my-wildfly-app
  name: wuar-demo-ombq
  namespace: jmesnil1-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: wuar-demo-ombq
status:
  loadBalancer: {}
